import { createSlice } from '@reduxjs/toolkit';

const data = [
  {
    productionUnit: 'Meuse',
    eicProd: '17W100P100P0076C',
    regroupementHydro: 'Meuse',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Jura-Vosges',
    eicProd: '17W100P100P0323L',
    regroupementHydro: 'Jura-Vosges',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Rhin',
    eicProd: '17W100P100P0327D',
    regroupementHydro: 'Rhin',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Nord-Ouest',
    eicProd: '',
    regroupementHydro: 'Nord-Ouest',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Rhône Nord',
    eicProd: '',
    regroupementHydro: 'Rhône',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Rhône Sud',
    eicProd: '17W100P100P0325H',
    regroupementHydro: 'Rhône',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Arve',
    eicProd: '',
    regroupementHydro: 'Alpes Nord',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Beaufortain',
    eicProd: '17W100P100P0326F',
    regroupementHydro: 'Alpes Nord',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Tarentaise',
    eicProd: '17W000001017800G',
    regroupementHydro: 'Alpes Nord',
    pmax: 1200,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 132,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Maurienne',
    eicProd: '17W100P100P0319C',
    regroupementHydro: 'Alpes Nord',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Romanche',
    eicProd: '17W100P100P0321P',
    regroupementHydro: 'Alpes Nord',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Drac',
    eicProd: '17W100P100P0320R',
    regroupementHydro: 'Alpes Nord',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Basse-Isère',
    eicProd: '17W000001017795K',
    regroupementHydro: 'Alpes Nord',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Durance-Verdon',
    eicProd: '17W000001017796I',
    regroupementHydro: 'Alpes Provence',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Alpes-Maritimes',
    eicProd: '17W000001017797G',
    regroupementHydro: 'Alpes Provence',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Adour-Gaves',
    eicProd: '17W000001017798E',
    regroupementHydro: 'Pyrénées',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Garonne-Ariège',
    eicProd: '17W000001017790U',
    regroupementHydro: 'Pyrénées',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Aude-Têt',
    eicProd: '17W000001017789F',
    regroupementHydro: 'Pyrénées',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Ardèche',
    eicProd: '17W000001017794M',
    regroupementHydro: 'Massif Central',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Tarn',
    eicProd: '17W000001017792Q',
    regroupementHydro: 'Massif Central',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Lot-Truyère',
    eicProd: '17W000001017788H',
    regroupementHydro: 'Massif Central',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Dordogne',
    eicProd: '17W000001017791S',
    regroupementHydro: 'Massif Central',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
  {
    productionUnit: 'Loire-Vienne',
    eicProd: '17W000001017791S',
    regroupementHydro: 'Massif Central',
    pmax: 1400,
    productionCategory: 'HYDRAULICS',
    productionCapacity: 232,
    unavailableCapacity: 0,
  },
];
const initialState = {
  items: data,
  error: {},
};

export const bilanSlice = createSlice({
  name: 'bilan',
  initialState,
  reducers: {
    loadBilanSuccess: (state, action) => {
      return { ...state, items: action.payload.items };
    },
    loadBilanFail: (state, action) => {
      return { ...state, error: action.payload.error };
    },
  },
});
export const { loadBilanSuccess, loadBilanFail } = bilanSlice.actions;

export default bilanSlice.reducer;
