/* eslint-disable import/prefer-default-export */
export const ProductionCategories = {
  BIOMASS: 'BIOMASS',

  FOSSIL_BROWN_COAL_LIGNITE: 'FOSSIL_BROWN_COAL_LIGNITE',
  FOSSIL_COAL_DERIVED_GAS: 'FOSSIL_COAL_DERIVED_GAS',
  FOSSIL_GAS: 'FOSSIL_GAS',
  FOSSIL_HARD_COAL: 'FOSSIL_HARD_COAL',
  FOSSIL_OIL: 'FOSSIL_OIL',
  FOSSIL_OIL_SHALE: 'FOSSIL_OIL_SHALE',
  FOSSIL_PEAT: 'FOSSIL_PEAT',

  GEOTHERMAL: 'GEOTHERMAL',

  HYDRO_PUMPED_STORAGE: 'HYDRO_PUMPED_STORAGE',
  HYDRO_RUN_OF_RIVER_AND_POUNDAGE: `HYDRO_RUN_OF_RIVER_AND_POUNDAGE`,
  HYDRO_WATER_RESERVOIR: 'HYDRO_WATER_RESERVOIR',
  HYDRAULICS: 'HYDRAULICS',

  MARINE: 'MARINE',
  NUCLEAR: 'NUCLEAR',
  OTHER_RENEWABLE: 'OTHER_RENEWABLE',
  SOLAR: 'SOLAR',
  WASTE: 'WASTE',
  WIND_OFFSHORE: 'WIND_OFFSHORE',
  WIND_ONSHORE: 'WIND_ONSHORE',
  OFFSHORE: 'OFFSHORE',
  TIDAL: 'TIDAL',
  OTHER: 'OTHER',
  ALL: 'ALL',
};
export const ProductionTypes = {
  BIOMASS: 'BIOMASS',

  FOSSIL_BROWN_COAL_LIGNITE: 'FOSSIL_BROWN_COAL_LIGNITE',
  FOSSIL_COAL_DERIVED_GAS: 'FOSSIL_COAL_DERIVED_GAS',
  FOSSIL_GAS: 'FOSSIL_GAS',
  FOSSIL_HARD_COAL: 'FOSSIL_HARD_COAL',
  FOSSIL_OIL: 'FOSSIL_OIL',
  FOSSIL_OIL_SHALE: 'FOSSIL_OIL_SHALE',
  FOSSIL_PEAT: 'FOSSIL_PEAT',

  GEOTHERMAL: 'GEOTHERMAL',

  HYDRO_PUMPED_STORAGE: 'HYDRO_PUMPED_STORAGE',
  HYDRO_RUN_OF_RIVER_AND_POUNDAGE: `HYDRO_RUN_OF_RIVER_AND_POUNDAGE`,
  HYDRO_WATER_RESERVOIR: 'HYDRO_WATER_RESERVOIR',

  MARINE: 'MARINE',
  NUCLEAR: 'NUCLEAR',
  OTHER_RENEWABLE: 'OTHER_RENEWABLE',
  SOLAR: 'SOLAR',
  WASTE: 'WASTE',
  WIND_OFFSHORE: 'WIND_OFFSHORE',
  WIND_ONSHORE: 'WIND_ONSHORE',
  TOTAL: 'TOTAL',
  OTHER: 'OTHER',
};
